from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, KeepTogether, Image, Table, TableStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
from Core.logger import *

logger = Logger().setup_logs()

class ReportGenerator:
    def __init__(self, level, level_1_data="", level_2_data="", level_3_data=""):
        self.styles = getSampleStyleSheet()
        self.styles.add(ParagraphStyle(name="FooterStyle", parent=self.styles["Normal"], alignment=1))
        self.styles.add(ParagraphStyle(name="TitleStyle", parent=self.styles["Title"], alignment=1))
        self.styles.add(ParagraphStyle(name="InfoStyle", parent=self.styles["Normal"], alignment=1))
        self.styles.add(ParagraphStyle(name='NormalStyle', parent=self.styles['BodyText'], alignment=0))
        self.styles.add(ParagraphStyle(name='CenteredHeading1', parent=self.styles['Heading1'], alignment=1))
        self.styles.add(ParagraphStyle(name='CenteredHeading2', parent=self.styles['Heading2'], alignment=0))
        self._gen_report(level, level_1_data, level_2_data, level_3_data)

    def _footer(self, canvas, doc):
        footer_para = Paragraph("Made with ♥ by Abhishek Tiwari", self.styles["FooterStyle"])
        w, h = footer_para.wrap(doc.width, doc.bottomMargin)
        footer_para.drawOn(canvas, doc.leftMargin, 10)

    def _title_page(self):
        story = []
        story.append(Spacer(1, 300))
        story.append(Paragraph("Data Analysis Report - Online Retail", self.styles["TitleStyle"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"Report Generated by: RetailApp Application", self.styles["InfoStyle"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph(f"Date: {datetime.today().strftime('%B %d, %Y')}", self.styles["InfoStyle"]))
        story.append(PageBreak())
        logger.info(f"Title Page Data Created for PDF.")
        return story
    
    def _level_type(self,level):
        story = []
        match level:
            case 1:
                story.append(Paragraph("LEVEL - 1 ANALYSIS", self.styles["CenteredHeading1"]))
            case 2:
                story.append(Paragraph("LEVEL - 2 ANALYSIS", self.styles["CenteredHeading1"]))
            case 3:
                story.append(Paragraph("LEVEL - 3 ANALYSIS", self.styles["CenteredHeading1"]))
        return story
        
    
    def _level_1_report(self, data):
        story = []
        story.append(Spacer(1, 6))
        story.append(Paragraph(data["description"], self.styles["NormalStyle"]))
        story.append(Spacer(1, 12))

        #table - column desc
        story.append(Paragraph("Column Descriptions", self.styles["CenteredHeading2"]))
        story.append(Spacer(1, 6))
        table_data = [["Column", "Description"]] 
        table_data += [[index, Paragraph(value, self.styles["NormalStyle"])] for index, value in data["column_descriptions"].items()]
        col_width = [100, 400]
        table = Table(table_data, colWidths=col_width, hAlign="LEFT")
        table.setStyle(
            TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
            ])
        )
        story.append(table)
        story.append(Spacer(1, 12))

        # data type table
        story.append(Paragraph("Column Data Types", self.styles["CenteredHeading2"]))
        story.append(Spacer(1, 6))
        table_data_type = [["Column", "Type", "Data Type"]] 
        table_data_type += [[Paragraph(index, self.styles["NormalStyle"]), Paragraph(value[0], self.styles["NormalStyle"]), Paragraph(value[1], self.styles["NormalStyle"])] for index,value in data["data_types"].items()]
        col_width_type = [100, 100, 100]
        table_data_type = Table(table_data_type, colWidths=col_width_type, hAlign="LEFT")
        table_data_type.setStyle(
            TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
            ])
        )
        story.append(table_data_type)
        story.append(Spacer(1, 12))

        #kpis
        story.append(Paragraph("Key Performance Indicators", self.styles["CenteredHeading2"]))
        story.append(Spacer(1, 6))
        table_data_kpi = [["Metric", "Value"]]
        table_data_kpi += [[Paragraph(index, self.styles["NormalStyle"]), Paragraph(value, self.styles["NormalStyle"])] for index, value in data["kpis"].items()]
        col_width_kpi= [100, 100]
        table_data_kpi = Table(table_data_kpi, colWidths=col_width_kpi, hAlign="LEFT")
        table_data_kpi.setStyle(
            TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
            ])
        )
        story.append(table_data_kpi)
        story.append(Spacer(1, 12))

        #interesting facts
        story.append(Paragraph("Interesting Facts", self.styles["CenteredHeading2"]))
        story.append(Spacer(1, 6))
        for index in data["interesting_facts"].keys():
            story.append(Paragraph(f"• {data["interesting_facts"][index]}", self.styles["NormalStyle"]))
            story.append(Spacer(1, 1))
        logger.info(f"Level 1 Data Created for PDF.")
        return story
    
    def _level_2_report(self, data):
        story = []
        story.append(Spacer(1, 12))
        plot_title = {
            "monthly_revenue_plot": "Monthly Revenue Trend",
            "yearly_revenue_plot": "Yearly Revenue Trend",
            "top_10_country_by_revenue": "Top 10 Countries by Revenue",
            "top_10_customer_by_purchase": "Top 10 Customer by Purchase by Country"
        }
        for key, title in plot_title.items():
            if key in data:
                block = KeepTogether([
                    Paragraph(f"{title}", self.styles["CenteredHeading2"]),
                    Spacer(1, 6),
                    Image(data[key], width=6.0*inch, height=3.5*inch),
                    Spacer(1, 12)
                ])
                story.append(block)
        logger.info(f"Level 2 Data Created for PDF.")
        return story
    
    def _level_3_report(self, data):
        story = []
        story.append(Spacer(1, 12))
        plot_title = {
            "top_10_country_by_no_of_customers": "Top 10 Country by No. of Customers",
            "top_10_country_qunatity_vs_revenue": "Quantity VS Revenue for Top 10 Countries",
            "top_10_product_by_quantity_sold": "Top 10 Products by Quantity Sold",
            "correlation_matrix_heatmap": "Correlation Matrix"
        }
        for key, title in plot_title.items():
            if key in data:
                block = KeepTogether([
                    Paragraph(f"{title}", self.styles["CenteredHeading2"]),
                    Spacer(1, 6),
                    Image(data[key], width=6.0*inch, height=3.5*inch),
                    Spacer(1, 12)
                ])
                story.append(block)
        logger.info(f"Level 3 Data Created for PDF.")
        return story
        
    
    def _gen_report(self, level, level_1_data, level_2_data, level_3_data):
        match level:
            case 1:
                story = self._title_page() + self._level_type(level) + self._level_1_report(level_1_data)
                doc = SimpleDocTemplate("Level_1_Report.pdf", pagesize=A4)
                logger.info(f"Writing Level 1 Data to PDF.")
                doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)
            case 2:
                story = self._title_page() + self._level_type(level) + self._level_1_report(level_1_data) + self._level_2_report(level_2_data)
                doc = SimpleDocTemplate("Level_2_Report.pdf", pagesize=A4)
                logger.info(f"Writing Level  Data to PDF.")
                doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)
            case 3:
                story = self._title_page() + self._level_type(level) + self._level_1_report(level_1_data) + self._level_2_report(level_2_data) + self._level_3_report(level_3_data)
                doc = SimpleDocTemplate("Level_3_Report.pdf", pagesize=A4)
                logger.info(f"Writing Level 3 Data to PDF.")
                doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)









        
        
